export type TopicVocabularyItem = {
  topic: string;
  words: string[];
};

export const topicVocabulary: TopicVocabularyItem[] = [
  {
    topic: "게임",
    words: ["game type","frequency","preference","games","daily life","effect","positive memory","game experience","favorite game","reason","device","phone","PC","console","gaming","first game experience","early game","first impression","enjoy","favorites","play games","with whom","memorable","gaming experience"],
  },
  {
    topic: "공연",
    words: ["performance","show","recently","attended","stage","tickets","audience","describe","atmosphere","reacted","performances","enjoy","reason","give","situation","want","sorry","problem","resolve","ever","cancel","plan","last time","details","example","plays","start","seeing","first time","memorable","play","watched","captivating","immersive","versatile","emotional depth","stage presence","well-crafted","live performance","expressive","thought-provoking","outstanding portrayal","auditorium","centrally located","spacious","modern interior","seating capacity","comfortable seating","excellent acoustics","state-of-the-art","frequently visit","various performances","get ready","make a reservation","head to the venue","arrive early","grab a snack","check the schedule","take my seat","enjoy the performance","take photos","reflect on the play","used to","gradually","developed an interest","preference","light-hearted","entertaining","nowadays","more sophisticated","meaningful","broadened perspective","unforgettable","outstanding performance","lead actor","breathtaking","emotionally moving","powerful message","dramatic scene","vivid memory","left a lasting impression"],
  },
  {
    topic: "공원",
    words: ["park","visit","makes","special","walking path","bench","trees","weekend","describe","scenery","atmosphere","activities","located","look","normally","typical","store","price","discount","buy","memorable","experience","happened","reason","enjoy","going","questions","park scenery","located near","peaceful","spacious","walking trail","greenery","well-maintained","relaxing atmosphere","go with friends","spend time outdoors","how often","visit regularly","take a walk","enjoy nature","have a picnic","relax on the grass","exercise","spend time alone","watch people","head back home","memorable experience","unforgettable moment","spend time with","hang out","special event","unexpected situation","sudden rain","have a great time","laugh together","cherish the memory","first became interested","back then","go with family","childhood memory","spend quality time","over time","gradually changed","prefer relaxing activities","enjoy alone time","become more meaningful","recently","last time I went","went to","enjoy the scenery","relax and unwind","take photos"],
  },
  {
    topic: "구직",
    words: ["looking","want","preparing","resume","interview","application","preparation","look","feel","stressed","manage","before","searching","checking","postings","post","comment","upload","followers","job search","job type","reasons","application steps","skills","strengths"],
  },
  {
    topic: "국내여행",
    words: ["indicated","survey","enjoy","traveling","favorite","reason","destination","plan","trip","took","youth","companions","pack","photos","interesting","unforgettable","experiences","travel","domestically","place","visit","childhood","memorable","thing","traveled","domestic","country","domestic travel","convenient","easy access","travel destination","scenic views","cultural experience","local food","popular spot","favorite location","relaxing getaway","vacation spots","popular destinations","nowadays","travel trend","seaside","mountains","city trips","overseas travel","short getaways","relaxing places","make a checklist","pack my luggage","travel essentials","toiletries","extra clothes","charger","important documents","book accommodation","plan the itinerary","double-check everything","engage in sightseeing","explore local attractions","indulge in local cuisine","cultural immersion","recreational activities","capture moments","portable devices","personal belongings","practical necessities","over the years","travel patterns","in the past","significant changes","more convenient","transportation options","digital booking","share on social media","personalized experiences","memorable trip","unforgettable experience","breathtaking scenery","explore a new place","encounter something unexpected","highlight of the trip","once-in-a-lifetime","create lasting memories","meaningful moment","leave a strong impression","unexpected experience","memorable journey","amusing moment","exciting adventure","scenic attraction","run into a problem","spontaneous event","make the trip special","vivid detail","remain unforgettable","childhood trip","family vacation","back when I was young","go with my parents","vivid memory","tourist attraction","scenic landscape","local specialty","what I remember the most","unforgettable moment"],
  },
  {
    topic: "사는지역",
    words: ["area","live","details","example","neighborhood","neighbors","community","friendly","apartment complex","describe","changes","seen","living","talk","transportation","people","routine","practice","stamina","team","living area","description","features","like most","reasons","time"],
  },
  {
    topic: "산",
    words: ["enjoy","hiking","usual","routine","hiking trail","backpack","hiking shoes","safety","describe","favorite","mountain","reason","feel","after","frequency","place","simply","memorable","moment","happened","good","points","body","prepare","stay","safe","start","liking","interesting","trail","visited","first","time","first time","long","hike","wear","shoes","clothes","climbed","mountains","nature","path","description"],
  },
  {
    topic: "쇼핑",
    words: ["shop","store","price","discount","buy","describe","memorable","shopping","experience","compare","online","stores","recent","grocery","companions","last","time","went","last time","days","changed","compared","problems","long","lines","special","memory","reason","talk","habits","frequency","first","become","interested","first time","anything","funny","exciting","shopping mall","retail store","centrally located","wide selection","affordable prices","trendy items","daily necessities","well-organized","frequently visit","go-to store","shopping habits","on a regular basis","once or twice a week","go shopping","buy daily necessities","go with friends","compare prices","enjoy browsing","memorable experience","unexpected situation","great deal","limited edition","impulse buying","stand out","customer service","make it special","feel satisfied","leave a lasting impression","shopping problem","defective item","out of stock","wrong size","billing error","ask for help","talk to the staff","request an exchange","solve the issue","handle the situation calmly","recently","the last time I went","go with a friend","browse items","make a purchase","try something new","enjoy the experience"],
  },
  {
    topic: "술집",
    words: ["visit","makes","special","drink menu","snacks","friends","atmosphere","describe","favorite","drinking","drinks","enjoy","reason","look","else","other","ever","memorable","experience","happened","go out for drinks","hang out with friends","casual atmosphere","order drinks","signature menu","light snacks","have a conversation","unwind after a long day","enjoy the vibe","spend quality time","over the years","drinking culture","in the past","nowadays","modern interior","wider selection","social atmosphere","customer preferences","still popular","noticeable changes","memorable incident","unexpected situation","lively atmosphere","run into someone","misunderstanding","handle the situation","stay calm","solve the problem","make it unforgettable","leave a strong impression","first time experience","back then","cozy atmosphere","dim lighting","go with friends","try new food","bar snacks","feel nervous","memorable moment"],
  },
  {
    topic: "여행",
    words: ["recent","trip","took","destination","plan","pack","photos","describe","memorable","place","visited","reason","compare","traveling","traveled","past","before","prepare","unexpected","things","happen","talk","childhood","companions","enjoy","doing","vacation","give","activities","experience","special","now","comparison","changes"],
  },
  {
    topic: "영화",
    words: ["movie","watched","recently","plot","genre","scene","review","movies","reason","describe","theater","experience","favorite","watch","actor","actress","recent","last","time","went","last time","enjoy","watching","questions","movie theater","located in","modern design","comfortable seating","large screen","surround sound","cozy atmosphere","frequently visit","blockbuster movie","memorable experience","renowned","acclaimed","versatile","filmography","breakthrough","prestigious","award-winning","controversy","public attention","reputation","suspenseful","heartwarming","captivating","realistic","unpredictable","emotional","storyline","cinematic","compelling","character","performance","chemistry","interpretation","message","ending","cinematography","soundtrack","impression","companion","preference","comfortable","similar taste","make plans","grab a meal","spend time together","share opinions","discuss the movie","quality time","film industry","evolution","production quality","advanced technology","visual effects","storytelling","audience preference","diversity","global influence","remain consistent","childhood favorite","animated film","nostalgic","simple storyline","over time","taste has changed","more complex","deeper meaning","mature themes","different preference","first became interested","back then","childhood experience","watch a movie","memorable film","develop an interest","preferences have changed","nowadays","the last time I went","go with a friend","arrive early","enjoy the movie"],
  },
  {
    topic: "요리",
    words: ["popular","traditional","food","country","reason","menu","taste","ingredients","daily","life","usual","meals","recipe","memorable","experience","eating","happened","typical","restaurants","last","time","last time","companions","special","dish","restaurant","explain","simply","prepare","meal","similar","different","signature dish","preparation","cooking process","seasoning","step-by-step","boil","stir-fry","adjust the taste","serve the dish","home-cooked meals","cooking routine","kitchen","follow a recipe","experiment with flavors","sense of accomplishment","cuisine","culinary tradition","cooking methods","flavor profile","spicy","mild","texture","cultural influence","unexpected difficulty","cooking mistake","burn the food","overseasoned","missing ingredient","adjust the recipe","solve the problem","stay calm","improvise","learn from the experience","first became interested","learn by watching","family member","teach me how to cook","cook together","kitchen experience","practice regularly","gain confidence","enjoyable activity"],
  },
  {
    topic: "운동",
    words: ["exercise","regularly","describe","routine","practice","stamina","team","sport","physical","activity","enjoy","reason","changed","life","health","watching","sports","favorite","player","person","playing","soccer","play","frequency","companions","stage","tickets","audience","game","watched","teammates","level up","strategy","game time","first","learn","taught","first time","usual","start","prepare","last","time","played","last time","feel","after","workout","type","enjoyment","change","benefits"],
  },
  {
    topic: "음악",
    words: ["music","listen","favorite","genre","playlist","lyrics","favorite song","describe","affects","mood","concert","musical","event","attended","stage","tickets","audience","show","indicated","survey","first","interested","listening","first time","time","listened","live","musician","play","violin","orchestra","three","listen to","favorite genre","daily life","musical event"],
  },
  {
    topic: "이웃",
    words: ["neighbors","community","friendly","apartment complex","interact","frequency","describe","positive","experience","neighbor","live","apartment","neighborhood","memorable","happened","changed","since","young","residential area","located in","convenient location","well-developed","local amenities","nearby facilities","grocery store","public transportation","quiet and peaceful","easy access","get along with","polite","close relationship","greet each other","have a conversation","help each other","casual interaction","run into","over the past ten years","has changed a lot","used to be","much more developed","modern buildings","improved infrastructure","more convenient than before","quality of life","memorable experience","unexpected event","take place","run into neighbors","community event","special occasion","exciting moment","share the experience","feel surprised","leave a lasting impression"],
  },
  {
    topic: "조깅산책",
    words: ["enjoy","jogging","walking","routine","route","shoes","pace","fresh air","describe","favorite","place","walk","reason","make","feel","frequency","memorable","time","happened","good","points","body","prepare","avoid","getting","start","liking","interesting","went","first","first time","long","take","usual","wear","outfit","enjoyment","favorite place","description","feelings","benefits"],
  },
  {
    topic: "집",
    words: ["describe","house","look","rooms","favorite","room","bedroom","living room","type","closet","live","apartment","three","four","activities","home","weekdays","weekends","lived","child","different","know","problems","experienced","something","mentioned","above","problem","details","example","description","features","favorite room","reason","change","years","living situation"],
  },
  {
    topic: "카페",
    words: ["favorite","cafe","makes","special","coffee","dessert","menu","atmosphere","describe","interior","memorable","experience","look","read","something","first","time","went","first time","cafes","shops","country","work","three","four","reason","description","details","story"],
  },
  {
    topic: "캠핑",
    words: ["camping","trip","went","destination","plan","pack","photos","preparations","make","tent","campfire","outdoor","packing list","describe","campsite","surroundings","enjoy","going","first","start","become","first time","give","situation","child","sorry","problem","need","resolve","camping trip","activities","experience","like most","description"],
  },
  {
    topic: "해변",
    words: ["beach","look","frequency","sand","waves","sunset","swim","memorable","trip","made","destination","plan","pack","photos","enjoy","going","three","reason","visit","activities","favorite beach","description","reasons"],
  },
  {
    topic: "해외여행",
    words: ["overseas","trip","took","destination","plan","pack","photos","interesting","thing","experienced","abroad","prepare","international","travel","indicated","survey","take","trips","activities","memorable","experience","traveling","reason","first","first time","someone","know","people","interested","foreign","country","visited","young","details","example","tourists","story","overseas trip","preparation","international travel"],
  },
  {
    topic: "휴일",
    words: ["spend","holidays","weekends","holiday plans","family","celebrate","special day","memorable","holiday","recently","activities","enjoy","doing","free","details","example","talk","country","celebrated","biggest","child","happened","reason","recent","free time","enjoyment"],
  },
  {
    topic: "SNS",
    words: ["social","media","platforms","post","comment","upload","followers","affect","daily","describe","positive","experience","using","reason","frequency","device","phone","tablet","first","start","time","first time","social media","use","daily life","effect","positive experience"],
  },
];

export const vocabularyMeanings: Record<string, string> = {
  "above": "위의",
  "abroad": "해외에",
  "acclaimed": "호평받는",
  "activities": "활동들",
  "activity": "활동",
  "actor": "배우",
  "actress": "여배우",
  "adjust the recipe": "레시피를 조절하다",
  "adjust the taste": "간을 맞추다",
  "advanced technology": "첨단 기술",
  "affect": "영향을 주다",
  "affects": "영향을 준다",
  "affordable prices": "합리적인 가격",
  "after": "이후에",
  "amusing moment": "재미있는 순간",
  "animated film": "애니메이션 영화",
  "anything": "무엇이든",
  "apartment": "아파트",
  "apartment complex": "아파트 단지",
  "application": "지원서",
  "area": "지역",
  "arrive early": "일찍 도착하다",
  "ask for help": "도움을 요청하다",
  "atmosphere": "분위기",
  "attended": "참석한",
  "audience": "관객",
  "audience preference": "관객 취향",
  "auditorium": "공연장",
  "avoid": "피하다",
  "award-winning": "수상 경력이 있는",
  "back then": "그 당시에는",
  "back when I was young": "어렸을 때",
  "backpack": "배낭",
  "bar snacks": "안주",
  "beach": "해변",
  "become": "되다",
  "become more meaningful": "더 의미 있게 되다",
  "bedroom": "침실",
  "before": "전에",
  "bench": "벤치",
  "biggest": "가장 큰",
  "billing error": "결제 오류",
  "blockbuster movie": "대작 영화",
  "body": "몸",
  "boil": "끓이다",
  "book accommodation": "숙소를 예약하다",
  "breakthrough": "도약의 계기",
  "breathtaking": "숨이 멎을 듯한",
  "breathtaking scenery": "숨이 멎을 듯한 풍경",
  "broadened perspective": "시야가 넓어짐",
  "browse items": "물건을 둘러보다",
  "burn the food": "음식을 태우다",
  "buy": "사다",
  "buy daily necessities": "생활 필수품을 사다",
  "cafe": "카페",
  "cafes": "카페들",
  "campfire": "캠프파이어",
  "camping": "캠핑",
  "campsite": "캠핑장",
  "cancel": "취소하다",
  "captivating": "사로잡는",
  "capture moments": "추억을 기록하다",
  "casual atmosphere": "편안한 분위기",
  "casual interaction": "가벼운 교류",
  "celebrate": "기념하다",
  "celebrated": "기념했다",
  "centrally located": "중심에 위치한",
  "changed": "바뀐",
  "changes": "변화",
  "character": "등장인물",
  "charger": "충전기",
  "check the schedule": "일정 확인하다",
  "checking": "확인하기",
  "chemistry": "배우 간 호흡",
  "cherish the memory": "추억으로 간직하다",
  "child": "아이",
  "childhood": "어린 시절",
  "childhood experience": "어린 시절 경험",
  "childhood favorite": "어릴 적 좋아했던 영화",
  "childhood memory": "어린 시절의 기억",
  "childhood trip": "어릴 적 여행",
  "cinematic": "영화 같은",
  "cinematography": "촬영 기법",
  "city trips": "도시 여행",
  "close relationship": "가까운 관계",
  "closet": "옷장",
  "clothes": "옷",
  "coffee": "커피",
  "comfortable": "편안한",
  "comfortable seating": "편안한 좌석",
  "comment": "댓글",
  "community": "공동체",
  "community event": "지역 행사",
  "companion": "동행인",
  "companions": "동행자들",
  "compare": "비교하다",
  "compare prices": "가격을 비교하다",
  "compared": "비교된",
  "compelling": "몰입하게 만드는",
  "concert": "콘서트",
  "console": "콘솔",
  "controversy": "논란",
  "convenient": "편리한",
  "convenient location": "편리한 위치",
  "cook together": "함께 요리하다",
  "cooking methods": "조리 방식",
  "cooking mistake": "요리 실수",
  "cooking process": "조리 과정",
  "cooking routine": "요리 루틴",
  "country": "나라",
  "cozy atmosphere": "아늑한 분위기",
  "create lasting memories": "오랫동안 기억에 남다",
  "cuisine": "요리",
  "culinary tradition": "요리 전통",
  "cultural experience": "문화적 경험",
  "cultural immersion": "문화 체험",
  "cultural influence": "문화적 영향",
  "customer preferences": "고객 취향",
  "customer service": "고객 서비스",
  "daily": "일상적인",
  "daily life": "일상생활",
  "daily necessities": "생활 필수품",
  "days": "날들",
  "deeper meaning": "더 깊은 의미",
  "defective item": "불량 상품",
  "describe": "설명하다",
  "dessert": "디저트",
  "destination": "목적지",
  "details": "세부사항",
  "develop an interest": "흥미가 생기다",
  "developed an interest": "흥미가 생기다",
  "device": "기기",
  "different": "다른",
  "different preference": "다른 취향",
  "digital booking": "온라인 예약",
  "dim lighting": "어두운 조명",
  "discount": "할인",
  "discuss the movie": "영화에 대해 이야기하다",
  "dish": "요리",
  "diversity": "다양성",
  "doing": "하는 것",
  "domestic": "국내의",
  "domestic travel": "국내 여행",
  "domestically": "국내에서",
  "double-check everything": "모든 것을 다시 확인하다",
  "dramatic scene": "극적인 장면",
  "drink menu": "음료 메뉴",
  "drinking": "술 마시기",
  "drinking culture": "음주 문화",
  "drinks": "음료",
  "early game": "초반 게임",
  "easy access": "접근성이 좋은",
  "eating": "먹기",
  "effect": "영향",
  "else": "그 밖에",
  "emotional": "감정적인",
  "emotional depth": "감정의 깊이",
  "emotionally moving": "감동적인",
  "encounter something unexpected": "예상치 못한 일을 겪다",
  "ending": "결말",
  "engage in sightseeing": "관광 활동을 하다",
  "enjoy": "즐기다",
  "enjoy alone time": "혼자 시간을 즐기다",
  "enjoy browsing": "구경하는 것을 즐기다",
  "enjoy nature": "자연을 즐기다",
  "enjoy the experience": "경험을 즐기다",
  "enjoy the movie": "영화를 즐기다",
  "enjoy the performance": "공연을 즐기다",
  "enjoy the scenery": "풍경을 즐기다",
  "enjoy the vibe": "분위기를 즐기다",
  "enjoyable activity": "즐거운 활동",
  "entertaining": "재미있는",
  "event": "행사",
  "ever": "언젠가",
  "evolution": "발전",
  "example": "예시",
  "excellent acoustics": "뛰어난 음향",
  "exciting": "신나는",
  "exciting adventure": "신나는 모험",
  "exciting moment": "흥미로운 순간",
  "exercise": "운동",
  "experience": "경험",
  "experienced": "경험한",
  "experiences": "경험들",
  "experiment with flavors": "맛을 실험하다",
  "explain": "설명하다",
  "explore a new place": "새로운 장소를 탐험하다",
  "explore local attractions": "지역 명소를 탐방하다",
  "expressive": "표현력이 풍부한",
  "extra clothes": "여벌 옷",
  "family": "가족",
  "family member": "가족 구성원",
  "family vacation": "가족 여행",
  "favorite": "가장 좋아하는",
  "favorite game": "가장 좋아하는 게임",
  "favorite location": "가장 좋아하는 장소",
  "favorite song": "가장 좋아하는 노래",
  "feel": "느끼다",
  "feel nervous": "긴장하다",
  "feel satisfied": "만족감을 느끼다",
  "feel surprised": "놀라움을 느끼다",
  "film industry": "영화 산업",
  "filmography": "출연 작품 목록",
  "first": "처음",
  "first became interested": "처음 관심을 갖게 되다",
  "first game experience": "첫 게임 경험",
  "first impression": "첫인상",
  "first time": "처음",
  "first time experience": "첫 경험",
  "flavor profile": "맛의 특징",
  "follow a recipe": "레시피를 따르다",
  "followers": "팔로워",
  "food": "음식",
  "foreign": "외국의",
  "four": "네 가지",
  "free": "자유로운",
  "frequency": "빈도",
  "frequently visit": "자주 방문하다",
  "fresh air": "신선한 공기",
  "friendly": "친근한",
  "friends": "친구들",
  "funny": "재미있는",
  "gain confidence": "자신감을 얻다",
  "game": "게임",
  "game experience": "게임 경험",
  "game time": "게임 시간",
  "game type": "게임 종류",
  "games": "게임들",
  "gaming": "게임하기",
  "genre": "장르",
  "get along with": "잘 지내다",
  "get ready": "준비하다",
  "getting": "얻기",
  "give": "주다",
  "global influence": "글로벌 영향",
  "go out for drinks": "술 마시러 가다",
  "go shopping": "쇼핑을 가다",
  "go with a friend": "친구와 함께 가다",
  "go with family": "가족과 함께 가다",
  "go with friends": "친구들과 가다",
  "go with my parents": "부모님과 가다",
  "go-to store": "자주 가는 가게",
  "going": "가는 것",
  "good": "좋은",
  "grab a meal": "식사를 하다",
  "grab a snack": "간단히 먹다",
  "gradually": "점차적으로",
  "gradually changed": "점차 변하다",
  "great deal": "좋은 가격의 거래",
  "greenery": "푸른 식물들",
  "greet each other": "서로 인사하다",
  "grocery": "식료품",
  "grocery store": "식료품점",
  "habits": "습관",
  "handle the situation": "상황에 대처하다",
  "handle the situation calmly": "침착하게 상황을 처리하다",
  "hang out": "어울려 놀다",
  "hang out with friends": "친구들과 어울리다",
  "happen": "일어나다",
  "happened": "일어났다",
  "has changed a lot": "많이 변했다",
  "have a conversation": "대화를 나누다",
  "have a great time": "즐거운 시간을 보내다",
  "have a picnic": "피크닉을 하다",
  "head back home": "집으로 돌아가다",
  "head to the venue": "공연장으로 가다",
  "health": "건강",
  "heartwarming": "감동적인",
  "help each other": "서로 돕다",
  "highlight of the trip": "여행의 하이라이트",
  "hike": "등산하다",
  "hiking": "등산",
  "hiking shoes": "등산화",
  "hiking trail": "등산로",
  "holiday": "휴일",
  "holiday plans": "휴일 계획",
  "holidays": "휴일들",
  "home": "집",
  "home-cooked meals": "집밥",
  "house": "집",
  "how often": "얼마나 자주",
  "immersive": "몰입감 있는",
  "important documents": "중요한 서류",
  "impression": "인상",
  "improved infrastructure": "개선된 기반 시설",
  "improvise": "즉흥적으로 대처하다",
  "impulse buying": "충동 구매",
  "in the past": "과거에는",
  "indicated": "표시한",
  "indulge in local cuisine": "지역 음식을 즐기다",
  "ingredients": "재료",
  "interact": "교류하다",
  "interested": "관심 있는",
  "interesting": "흥미로운",
  "interior": "인테리어",
  "international": "국제적인",
  "interpretation": "해석",
  "interview": "면접",
  "jogging": "조깅",
  "kitchen": "주방",
  "kitchen experience": "주방 경험",
  "know": "알다",
  "large screen": "큰 스크린",
  "last": "지난",
  "last time": "지난번",
  "last time I went": "마지막으로 갔을 때",
  "laugh together": "함께 웃다",
  "lead actor": "주연 배우",
  "learn": "배우다",
  "learn by watching": "보면서 배우다",
  "learn from the experience": "경험을 통해 배우다",
  "leave a lasting impression": "오랫동안 기억에 남다",
  "leave a strong impression": "강한 인상을 남기다",
  "left a lasting impression": "오랫동안 인상에 남다",
  "level up": "레벨을 올리다",
  "life": "생활",
  "light snacks": "가벼운 안주",
  "light-hearted": "가벼운",
  "liking": "좋아함",
  "limited edition": "한정판",
  "lines": "대사",
  "listen": "듣다",
  "listened": "들었다",
  "listening": "듣기",
  "live": "살다",
  "live performance": "라이브 공연",
  "lived": "살았다",
  "lively atmosphere": "활기찬 분위기",
  "living": "사는",
  "living room": "거실",
  "local amenities": "생활 편의 시설",
  "local food": "지역 음식",
  "local specialty": "지역 특산물",
  "located": "위치한",
  "located in": "~에 위치한",
  "located near": "근처에 위치한",
  "long": "오래",
  "look": "모습",
  "looking": "찾는 중",
  "lyrics": "가사",
  "made": "만든",
  "make": "만들다",
  "make a checklist": "체크리스트를 만들다",
  "make a purchase": "구매하다",
  "make a reservation": "예약하다",
  "make it special": "특별하게 만들다",
  "make it unforgettable": "잊을 수 없게 만들다",
  "make plans": "계획을 세우다",
  "make the trip special": "여행을 특별하게 만들다",
  "makes": "만들어 준다",
  "manage": "관리하다",
  "mature themes": "성숙한 주제",
  "meal": "식사",
  "meals": "식사들",
  "meaningful": "의미 있는",
  "meaningful moment": "의미 있는 순간",
  "media": "미디어",
  "memorable": "기억에 남는",
  "memorable experience": "기억에 남는 경험",
  "memorable film": "기억에 남는 영화",
  "memorable incident": "기억에 남는 사건",
  "memorable journey": "기억에 남는 여행",
  "memorable moment": "기억에 남는 순간",
  "memorable trip": "기억에 남는 여행",
  "memory": "기억",
  "mentioned": "언급한",
  "menu": "메뉴",
  "message": "메시지",
  "mild": "담백한",
  "missing ingredient": "재료가 부족한",
  "misunderstanding": "오해",
  "modern buildings": "현대식 건물",
  "modern design": "현대적인 디자인",
  "modern interior": "현대적인 내부",
  "moment": "순간",
  "mood": "기분",
  "more complex": "더 복잡한",
  "more convenient": "더 편리한",
  "more convenient than before": "예전보다 더 편리한",
  "more sophisticated": "더 세련된",
  "mountain": "산",
  "mountains": "산",
  "movie": "영화",
  "movie theater": "영화관",
  "movies": "영화들",
  "much more developed": "훨씬 더 발전한",
  "music": "음악",
  "musical": "뮤지컬",
  "musician": "음악가",
  "nearby facilities": "근처 시설",
  "need": "필요하다",
  "neighbor": "이웃",
  "neighborhood": "동네",
  "neighbors": "이웃들",
  "normally": "보통",
  "nostalgic": "향수를 불러일으키는",
  "noticeable changes": "눈에 띄는 변화",
  "nowadays": "요즘에는",
  "on a regular basis": "정기적으로",
  "once or twice a week": "일주일에 한두 번",
  "once-in-a-lifetime": "평생 한 번뿐인",
  "online": "온라인",
  "orchestra": "오케스트라",
  "order drinks": "술을 주문하다",
  "other": "다른",
  "out of stock": "품절된",
  "outdoor": "야외의",
  "outfit": "복장",
  "outstanding performance": "뛰어난 공연",
  "outstanding portrayal": "뛰어난 연기 표현",
  "over the past ten years": "지난 10년 동안",
  "over the years": "수년간",
  "over time": "시간이 지나면서",
  "overseas": "해외",
  "overseas travel": "해외 여행",
  "overseasoned": "간이 너무 센",
  "pace": "속도",
  "pack": "짐을 싸다",
  "pack my luggage": "짐을 싸다",
  "packing list": "짐 목록",
  "park": "공원",
  "park scenery": "공원 풍경",
  "past": "과거",
  "PC": "컴퓨터",
  "peaceful": "평화로운",
  "people": "사람들",
  "performance": "공연",
  "performances": "공연들",
  "person": "사람",
  "personal belongings": "개인 소지품",
  "personalized experiences": "개인화된 경험",
  "phone": "전화",
  "photos": "사진들",
  "physical": "신체적인",
  "place": "장소",
  "plan": "계획",
  "plan the itinerary": "일정을 계획하다",
  "platforms": "플랫폼들",
  "play": "하다",
  "played": "했다",
  "player": "플레이어",
  "playing": "하는 중",
  "playlist": "재생목록",
  "plays": "한다",
  "plot": "줄거리",
  "points": "요점들",
  "polite": "예의 바른",
  "popular": "인기 있는",
  "popular destinations": "인기 있는 여행지",
  "popular spot": "인기 있는 장소",
  "portable devices": "휴대용 기기",
  "positive": "긍정적인",
  "positive memory": "좋은 기억",
  "post": "게시물",
  "postings": "게시글들",
  "powerful message": "강한 메시지",
  "practical necessities": "실용적인 필수품",
  "practice": "연습",
  "practice regularly": "꾸준히 연습하다",
  "prefer relaxing activities": "편안한 활동을 선호하다",
  "preference": "선호",
  "preferences have changed": "취향이 변하다",
  "preparation": "준비",
  "preparations": "준비 과정",
  "prepare": "준비하다",
  "preparing": "준비하는 중",
  "prestigious": "권위 있는",
  "price": "가격",
  "problem": "문제",
  "problems": "문제들",
  "production quality": "제작 퀄리티",
  "public attention": "대중의 관심",
  "public transportation": "대중교통",
  "quality of life": "삶의 질",
  "quality time": "의미 있는 시간",
  "questions": "질문들",
  "quiet and peaceful": "조용하고 평화로운",
  "reacted": "반응했다",
  "read": "읽다",
  "realistic": "현실적인",
  "reason": "이유",
  "recent": "최근의",
  "recently": "최근에",
  "recipe": "레시피",
  "recreational activities": "여가 활동",
  "reflect on the play": "공연을 되돌아보다",
  "regularly": "규칙적으로",
  "relax and unwind": "휴식을 취하다",
  "relax on the grass": "잔디에 누워 쉬다",
  "relaxing atmosphere": "편안한 분위기",
  "relaxing getaway": "편안한 휴식 여행",
  "relaxing places": "휴식하기 좋은 장소",
  "remain consistent": "여전히 유지되다",
  "remain unforgettable": "잊히지 않다",
  "renowned": "저명한",
  "reputation": "평판",
  "request an exchange": "교환을 요청하다",
  "residential area": "주거 지역",
  "resolve": "해결하다",
  "restaurant": "식당",
  "restaurants": "식당들",
  "resume": "이력서",
  "retail store": "소매점",
  "review": "감상평",
  "room": "방",
  "rooms": "방들",
  "route": "경로",
  "routine": "일과",
  "run into": "우연히 마주치다",
  "run into a problem": "문제를 겪다",
  "run into neighbors": "이웃을 우연히 만나다",
  "run into someone": "우연히 누군가를 만나다",
  "safe": "안전한",
  "safety": "안전",
  "sand": "모래",
  "scene": "장면",
  "scenery": "풍경",
  "scenic attraction": "경치 좋은 명소",
  "scenic landscape": "아름다운 풍경",
  "scenic views": "경치 좋은 풍경",
  "searching": "검색하기",
  "seaside": "해변",
  "seasoning": "양념",
  "seating capacity": "수용 인원",
  "seeing": "보기",
  "seen": "본",
  "sense of accomplishment": "성취감",
  "serve the dish": "요리를 제공하다",
  "share on social media": "소셜미디어에 공유하다",
  "share opinions": "의견을 나누다",
  "share the experience": "경험을 공유하다",
  "shoes": "신발",
  "shop": "가게",
  "shopping": "쇼핑",
  "shopping habits": "쇼핑 습관",
  "shopping mall": "쇼핑몰",
  "shopping problem": "쇼핑 중 문제",
  "shops": "가게들",
  "short getaways": "짧은 여행",
  "show": "공연",
  "signature dish": "대표 요리",
  "signature menu": "대표 메뉴",
  "significant changes": "큰 변화",
  "similar": "비슷한",
  "similar taste": "비슷한 취향",
  "simple storyline": "단순한 줄거리",
  "simply": "단순히",
  "since": "이후로",
  "situation": "상황",
  "snacks": "간식",
  "soccer": "축구",
  "social": "소셜",
  "social atmosphere": "사교적인 분위기",
  "solve the issue": "문제를 해결하다",
  "solve the problem": "문제를 해결하다",
  "someone": "누군가",
  "something": "무언가",
  "sorry": "미안한",
  "soundtrack": "배경음악",
  "spacious": "넓은",
  "special": "특별한",
  "special day": "특별한 날",
  "special event": "특별한 행사",
  "special occasion": "특별한 순간",
  "spend": "보내다",
  "spend quality time": "의미 있는 시간을 보내다",
  "spend time alone": "혼자 시간을 보내다",
  "spend time outdoors": "야외에서 시간을 보내다",
  "spend time together": "함께 시간을 보내다",
  "spend time with": "함께 시간을 보내다",
  "spicy": "매운",
  "spontaneous event": "즉흥적인 일",
  "sport": "스포츠",
  "sports": "스포츠들",
  "stage": "무대",
  "stage presence": "무대 장악력",
  "stamina": "체력",
  "stand out": "눈에 띄다",
  "start": "시작하다",
  "state-of-the-art": "최첨단의",
  "stay": "머무르다",
  "stay calm": "침착함을 유지하다",
  "step-by-step": "단계별로",
  "still popular": "여전히 인기 있는",
  "stir-fry": "볶다",
  "store": "상점",
  "stores": "상점들",
  "story": "이야기",
  "storyline": "줄거리",
  "storytelling": "스토리텔링",
  "strategy": "전략",
  "stressed": "스트레스를 받은",
  "sudden rain": "갑작스러운 비",
  "sunset": "노을",
  "surround sound": "입체 음향",
  "surroundings": "주변 환경",
  "survey": "설문",
  "suspenseful": "긴장감 있는",
  "swim": "수영하다",
  "tablet": "태블릿",
  "take": "가져가다",
  "take a walk": "산책하다",
  "take my seat": "자리에 앉다",
  "take photos": "사진 찍다",
  "take place": "발생하다",
  "talk": "이야기하다",
  "talk to the staff": "직원과 이야기하다",
  "taste": "맛",
  "taste has changed": "취향이 변하다",
  "taught": "가르쳐 주었다",
  "teach me how to cook": "요리를 가르쳐 주다",
  "team": "팀",
  "teammates": "팀원들",
  "tent": "텐트",
  "texture": "식감",
  "the last time I went": "마지막으로 갔을 때",
  "theater": "극장",
  "thing": "것",
  "things": "것들",
  "thought-provoking": "생각을 하게 만드는",
  "three": "세 가지",
  "tickets": "티켓",
  "time": "시간",
  "toiletries": "세면도구",
  "took": "갔다",
  "tourist attraction": "관광 명소",
  "tourists": "관광객들",
  "traditional": "전통적인",
  "trail": "길",
  "transportation": "교통수단",
  "transportation options": "교통 수단",
  "travel": "여행",
  "travel destination": "여행지",
  "travel essentials": "여행 필수품",
  "travel patterns": "여행 방식",
  "travel trend": "여행 트렌드",
  "traveled": "여행했다",
  "traveling": "여행하기",
  "trees": "나무들",
  "trendy items": "유행하는 상품",
  "trip": "여행",
  "trips": "여행들",
  "try new food": "새로운 음식을 먹다",
  "try something new": "새로운 것을 시도하다",
  "type": "종류",
  "typical": "전형적인",
  "unexpected": "예상치 못한",
  "unexpected difficulty": "예상치 못한 어려움",
  "unexpected event": "예상치 못한 일",
  "unexpected experience": "예상치 못한 경험",
  "unexpected situation": "예상치 못한 상황",
  "unforgettable": "잊을 수 없는",
  "unforgettable experience": "잊을 수 없는 경험",
  "unforgettable moment": "잊을 수 없는 순간",
  "unpredictable": "예측할 수 없는",
  "unwind after a long day": "하루를 마치고 쉬다",
  "upload": "업로드하다",
  "used to": "과거에는 ~하곤 했다",
  "used to be": "예전에는 ~였다",
  "using": "사용하기",
  "usual": "평소의",
  "vacation": "휴가",
  "vacation spots": "휴가지",
  "various performances": "다양한 공연",
  "versatile": "다재다능한",
  "violin": "바이올린",
  "visit": "방문하다",
  "visit regularly": "정기적으로 방문하다",
  "visited": "방문했다",
  "visual effects": "시각 효과",
  "vivid detail": "생생한 세부 묘사",
  "vivid memory": "생생한 기억",
  "walk": "걷다",
  "walking": "걷기",
  "walking path": "산책로",
  "walking trail": "산책로",
  "want": "원하다",
  "watch": "보다",
  "watch a movie": "영화를 보다",
  "watch people": "사람들을 구경하다",
  "watched": "봤다",
  "watching": "보기",
  "waves": "파도",
  "wear": "입다",
  "weekdays": "평일",
  "weekend": "주말",
  "weekends": "주말들",
  "well-crafted": "잘 만들어진",
  "well-developed": "잘 발달된",
  "well-maintained": "잘 관리된",
  "well-organized": "잘 정리된",
  "went": "갔다",
  "went to": "~에 갔다",
  "what I remember the most": "가장 기억에 남는 것",
  "wide selection": "다양한 선택지",
  "wider selection": "더 다양한 선택지",
  "application steps": "지원 절차",
  "benefits": "장점",
  "camping trip": "캠핑 여행",
  "change": "변화",
  "climbed": "올랐다",
  "comparison": "비교",
  "description": "묘사",
  "enjoyment": "즐거움",
  "favorite beach": "가장 좋아하는 해변",
  "favorite genre": "가장 좋아하는 장르",
  "favorite place": "가장 좋아하는 장소",
  "favorite room": "가장 좋아하는 방",
  "favorites": "좋아하는 것들",
  "features": "특징",
  "feelings": "느낌",
  "free time": "여가 시간",
  "gaming experience": "게임 경험",
  "international travel": "해외여행",
  "job search": "구직 활동",
  "job type": "직무 유형",
  "like most": "가장 좋아하다",
  "listen to": "~을 듣다",
  "living area": "사는 지역",
  "living situation": "주거 상황",
  "musical event": "음악 행사",
  "nature": "자연",
  "now": "지금",
  "overseas trip": "해외여행",
  "path": "길",
  "play games": "게임을 하다",
  "positive experience": "긍정적인 경험",
  "reasons": "이유들",
  "skills": "기술",
  "social media": "소셜 미디어",
  "strengths": "강점",
  "use": "사용하다",
  "with whom": "누구와 함께",
  "years": "몇 년",
  "work": "일",
  "workout": "운동",
  "wrong size": "사이즈가 맞지 않는",
  "young": "어린",
  "youth": "청소년기",
};
